-- Create user
CREATE USER HELCIODASILVA IDENTIFIED BY password;
GRANT RESOURCE TO HELCIODASILVA;
GRANT CONNECT TO HELCIODASILVA;
GRANT CREATE VIEW TO HELCIODASILVA;
GRANT CREATE SESSION TO HELCIODASILVA;
GRANT UNLIMITED TABLESPACE TO HELCIODASILVA;