version: '2'
services:
    jenkins:
        container_name: jenkins
        build:
            context: .
        privileged: true
        restart: always
        ports:
            - "8005:8080"
            - "50000:50000"
        volumes:
            - ./jenkins-data:/var/jenkins_home/
            - /var/run/docker.sock:/var/run/docker.sock
#    node:
#        image: jeffersonsouza/jenkins:slave-node
#        privileged: true
#        ports:
#            - 22
#        volumes_from:
#            - jenkins
#    php:
#        image: jeffersonsouza/jenkins:slave-php
#        privileged: true
#        ports:
#            - 22
#        volumes_from:
#            - jenkins
#    php56:
#        image: jeffersonsouza/jenkins:slave-php5
#        privileged: true
#        ports:
#            - 22
#        volumes_from:
#            - jenkins
#volumes:
#    jenkins-data:
#        driver: local
